default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: huysmans
  password: 123456
  host: localhost
  database: app_development

test:
  <<: *default
  username: huysmans
  password: 123456
  host: localhost
  database: app_test

production:
  <<: *default
  database: app_production
  username: huysmans
  password: 123456