default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>

development:
  <<: *default
#  username: huysmans
#  password: 123456
#  host: localhost
  database: leviathan_development

test:
  <<: *default
#  username: huysmans
#  password: 123456
#  host: localhost
  database: leviathan_test

production:
  <<: *default
  database: leviathan_production
#  username: huysmans
#  password: 123456